### ISSUE TITLE
Feat: Add ability to completely disable leave / edit logging

### ISSUE THREAD

**Issue by bredo228** [Sonnet-Discord/sonnet-py#108]
Currently there's no way to be able to completely disable leave or edit logging as they fall back to join logs and message logs respectively, making it so there is no way to disable leave / edit logging without disabling join / message logging.

**Comment by ultrabear** [comment]
This could be best implemented by `set-leave-log-is-join-log` and `set-edit-log-is-message-log` commands in administration, although they are wordy

**Comment by ultrabear** [comment]
did some hacking and found the largest native command is 25 chars, which the first command here matches and the second command beats by 2, i think at some point adding a max length to commands in the specification is good but there is a precedent for allowing commands to be this long, especially when it is hard to find a shorter name, so it should be fine to implement with the idiomatic names

**Comment by ultrabear** [comment]
settled on `edit-log-is-message-log` and `leave-log-is-join-log` for db config names

**Comment by ultrabear** [comment]
closing as implemented
