### ISSUE TITLE
Purge command

### ISSUE THREAD

**Issue by Saragon4005** [Sonnet-Discord/sonnet-py#30]
Add a purge command that can mass delete messages based on certain criteria like number of messages and which user posted them.
Additional enhancements (optional)
 * content/regex based filtering
 * attachment based filtering
 * mention based filtering
 * max age of message

**Comment by ultrabear** [comment]
May wanna skip this considering mantaro has a purge command that works fine already

**Comment by ultrabear** [comment]
IM ADDING IT ANYWAYS :trollface:
