### ISSUE TITLE
Moderator and Admin role permissions

### ISSUE THREAD

**Issue by Saragon4005** [Sonnet-Discord/sonnet-py#31]
Allow specific roles to have moderator and admin permissions even if the roles don't have the discord permissions associated with these internal permissions.

**Comment by ultrabear** [comment]
this shouldent be too hard to pass admin and mod roles into mconf on parse_permissions, and another lib function to parse role adding should be put in place for this, ill do this one

**Comment by ultrabear** [comment]
Completed: 3224d3c2fd271f19a2372b943b82f4f45eb9a61d
