### ISSUE TITLE
Add configuration upload

### ISSUE THREAD

**Issue by Saragon4005** [Sonnet-Discord/sonnet-py#32]
Configuration data can be downloaded using the gdpr command. This data should be able to be reintegrated into sonnet, based on a file upload from discord. This would make it easy for guild admins to move between different instances of sonnet.
#### Extra considerations
The file needs to be verified to make sure it's not a zip bomb or other malicious file that could cause issues with the entire currently running instance.

**Comment by ultrabear** [comment]
`git tag things-that-give-me-nightmares`

**Comment by ultrabear** [comment]
Note to anyone taking this task on:
- letting people upload files direct to the db has uncountable security flaws, do not go near this unless you absolutely know what you are doing

**Comment by ultrabear** [comment]
This was "added" in the form of gztodb.py, letting guild owners (the end end users) have direct access to upload to the db is just a bad idea
