### ISSUE TITLE
Documentation on binary formats

### ISSUE THREAD

**Issue by Saragon4005** [Sonnet-Discord/sonnet-py#33]
Sonnet includes several custom binary file formats made to maximize speed or storage efficiency. These formats aren't well documented and can confuse someone new to the code base.

**Comment by ultrabear** [comment]
Binary formats to document:
- SFDBC : SnowFlake DataBase Cache
  - Cache format used to store data from database per guild
  - Loads in ramfs and is faster than pinging database
- VNUM : Variable width binary NUMbers
  - Format to compress binary storage of numbers
- WLC : WordList Cache
  - Cache format to speed up grabbing words from wordlist for infractionIDs
- SONNETAES : Sonnet AES Format
  - An AES-CTR w/ HMAC Wrapper for python fileio
  - Used to encrypt data on disk

**Comment by ultrabear** [comment]
https://github.com/Sonnet-Discord/sonnet-discord.github.io/commit/4dfc72e6b209928c73b5b2297ee34e4cc9621ccc
