### ISSUE TITLE
Antispam variable mute time

### ISSUE THREAD

**Issue by Saragon4005** [Sonnet-Discord/sonnet-py#34]
Currently whenever anti spam triggers it mutes the offender for a set time. Currently this is a hard coded value that guilds cannot configure, this would add an option to change how long the mute lasts per guild.

**Comment by ultrabear** [comment]
god i should make this already it would take a good 5 seconds

**Comment by ultrabear** [comment]
6736bbbd8a61568f4051e0da08cee44df644f448  
took a bit more than 5 seconds but 20 minutes is like nothing
