### ISSUE TITLE
Multi thread mainloop

### ISSUE THREAD

**Issue by Saragon4005** [Sonnet-Discord/sonnet-py#35]
Something about allowing parallel processing on messages? ask @ultrabear for more info

**Comment by ultrabear** [comment]
Clarification:
- refactor on-message blacklist, statistics, antispam, regex notifier to all run in parallel
  - need to ensure threading overhead doesnt make it slower
  - need to ensure variables arent called by multiple threads, halting processing

**Comment by ultrabear** [comment]
So considering the GIL this is just not possible in cpython
