### ISSUE TITLE
Empty config command return current config

### ISSUE THREAD

**Issue by Saragon4005** [Sonnet-Discord/sonnet-py#38]
Whenever a configuration command is ran without any arguments the command should return the current setting.
This is already the case for some commands, but not all.

**Comment by Saragon4005** [comment]
#40 works on this

**Comment by ultrabear** [comment]
84a0c822a8a0f8ac18f2dfa3f0c032537e6b2e67 works on this

**Comment by ultrabear** [comment]
1ced94ed5a5049f879a68785583655b6827eb35d works on this

**Comment by ultrabear** [comment]
Completed: 2f749916e9323946a30bbe68f93bf1ce4d17d34b
