### ISSUE TITLE
Comprehensive setup guide

### ISSUE THREAD

**Issue by mckinley360** [Sonnet-Discord/sonnet-py#39]
If we want to encourage users to run their own instance of Sonnet, there needs to be a well written, easy to follow, and comprehensive setup guide. In addition, the embarrassing one in place now is already outdated due to new dependencies.

**Comment by ultrabear** [comment]
@Saragon4005 please asdifhbdsf its been months

**Comment by ultrabear** [comment]
https://github.com/Sonnet-Discord/sonnet-discord.github.io/commit/a2bc96664f2f77e593072159815e4b0f7294aa27
it exists its been done holy shit that took so long to get done
@Saragon4005 you are in charge of fixing grammar errors and whatever the guide is proper now (dont forget to use ./buildpush.sh to properly update the bhtml and push to gh-pages)
