### ISSUE TITLE
Charantispam

### ISSUE THREAD

**Issue by ultrabear** [Sonnet-Discord/sonnet-py#54]
add character based antispam  
the system would operate alongside the normal antispam  
it should have 3 points:
- cooldown time
- message count to trigger it checking
- amount of characters allowed before triggering antispam  

by also using message counts we avoid issues where someone needs to post a single large message and gets muted, a serious issue in other moderation bots on discord

**Comment by ultrabear** [comment]
this feature is so simple it just needs 3 datapoints i could even like piggyback asam for 2 points yeah ill do that ig whatever
woo binary formats

**Comment by ultrabear** [comment]
im leaving this here
```py
time.time() -> float
```
that lying piece of shit
returns _local time_
python has betrayed me

**Comment by Saragon4005** [comment]
yeah I absolutely hate this, I am so glad this is getting changed in dpy2.0 cuz it makes handling time just freaking impossible

**Comment by Saragon4005** [comment]
I know, but dpy did similar shit too, this is easy enough to bypass on dpy its a nightmare.
